#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0
echo "$FILES" | xargs pnpm oxfmt --write --no-error-on-unmatched-pattern
echo "$FILES" | xargs git add

exit 0
