/* eslint-disable perfectionist/sort-objects */
export default {
  Pioneer: 1,
  Infantry: 2,
  Jeep: 6,
  Artillery: 7,
  HeavyArtillery: 12,
  Sniper: 14,
  Flamethrower: 15,
  Saboteur: 16,
  FighterJet: 18,
  AcidBomber: 22,
  XFighter: 25,
  Medic: 26,
  Dinosaur: 36,
  SuperTank: 38,
  HumveeAvenger: 39,
  Octopus: 43,
  Dragon: 44,
  Bear: 45,
  Alien: 46,
  Zombie: 47,
  Ogre: 48,
  Brute: 49,
  Commander: 50,
  Cannon: 51,
  SuperAPU: 52,
  BazookaBear: 53,
  AIU: 54,
  InfernoJetpack: 55,
  Scientist: 56,
} as const;
/* eslint-enable perfectionist/sort-objects */
